### ISSUE TITLE
jenkins-cli connection to containerized jenkins server gets chunked 

### ISSUE THREAD

**Issue by clavisinsight** [aespinosa/docker-jenkins#24]
Hi there,

Started the container:
sudo docker run -d -P -name="docker-jenkins" docker-jenkins

Using the jenkins-cli on from my desktop:
java -jar jenkins-cli.jar -s http://jenkins.example.com:49153/ help

> Aug 09, 2014 5:35:08 PM hudson.remoting.SynchronousCommandTransport$ReaderThread run
> SEVERE: I/O error in channel Chunked connection to http://jenkins.example.com:49153/cli
> java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
>   at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
>   at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
>   at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
>   at  hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
>   at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
> 
> Exception in thread "main" hudson.remoting.RequestAbortedException: > hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
>   at hudson.remoting.RequestAbortedException.wrapForRethrow(RequestAbortedException.java:41)
>   at hudson.remoting.RequestAbortedException.wrapForRethrow(RequestAbortedException.java:34)
>   at hudson.remoting.Request.call(Request.java:174)
>   at hudson.remoting.Channel.call(Channel.java:739)
>   at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:168)
>   at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
>   at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1122)
>   at hudson.cli.CLI.<init>(CLI.java:145)
>   at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
>   at hudson.cli.CLI._main(CLI.java:459)
>   at hudson.cli.CLI.main(CLI.java:382)
> Caused by: hudson.remoting.RequestAbortedException: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
>   at hudson.remoting.Request.abort(Request.java:299)
>   at hudson.remoting.Channel.terminate(Channel.java:802)
>   at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
> Caused by: java.io.StreamCorruptedException: invalid stream header: 0A0A0A0A
>   at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
>   at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
>   at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
>   at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
>   at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

This is not reproducible if jenkins is running directly on the server (outside the container).
Any ideas what might be missing?

Many thanks,
Artur Martins

**Comment by anthonygreen** [comment]
Is this issue fixed?

**Comment by aespinosa** [comment]
Sorry I wasn't clear. The issue referenced in JIRA says that the JNLP port also needs to be exposed as I mentioned earlier.  Since it is dynamically defined, you would have to either [1] set it statically or [2] figure out a way to expose it later once it has been defined.

**Comment by astubbs** [comment]
For future readers:

http://jenkins-ci.361315.n4.nabble.com/What-port-does-JNLP-use-td3550072.html

> But you can also set a fixed value in the Jenkins system configuration (Manage Jenkins -> Configure System -> Tick check-box "Enable security", then see "TCP port for JNLP slave agents"). Having a fixed value is probably simpler to configure in firewalls. 

> Cheers, 
> Simon.

**Comment by anthonygreen** [comment]
Addendum for future readers you can  programmatically set the JNLP port with curl and a POST request 

     curl -X POST -d 'json=%7B%22useSecurity%22%3A+%7B%22slaveAgentPort%22%3A+%7B%22type%22%3A+%22fixed%22%2C+%22value%22%3A+%222230%22%7D%7D%2C+%22core%3Aapply%22%3A+%22true%22%7D' --header 'Content-Type: application/x-www-form-urlencoded' http://localhost:8080//configureSecurity/configure
