### ISSUE TITLE
Cannot mount volume using  -v <host-volume>:/jenkins

### ISSUE THREAD

**Issue by opicaud** [aespinosa/docker-jenkins#27]
Hey :-)

When I try to run your jenkins docker image, it stucks at the Initializing state. 

![image](https://cloud.githubusercontent.com/assets/1059698/5692175/9e18e78e-98ea-11e4-9dda-cb36f68c5d5e.png)

Here is my comand : 

docker run -P -v volume-on-host:/jenkins aespinosa/jenkins

Have you got an idea of this issue ?

Thank you

Olivier

**Comment by aespinosa** [comment]
Hi,

Sorry I can't replicate the situation on my machine. It goes in the "initializing" state for a while but proceeds forward.

**Comment by opicaud** [comment]
Yes I agree. Sorry for this...
