### ISSUE TITLE
Add Jenkins Follower and Plugin Configs to Subfolder of Dockerfile?

### ISSUE THREAD

**Issue by AnneTheAgile** [aespinosa/docker-jenkins#28]
I read #10 about how to add Git that you would like to have it separate and I think that makes sense. Two questions about your thoughts.

1.Plugins; I have quite a few plugins we need to make Jenkins work for us. How do you suggest adding them in to the Docker? 

2.Client-Server, Leader-Follower ; This Dockerfile is for a single isolated master, and some situations will need to have Agent machines running builds. How do you suggest doing that?

It seems to me as you suggested for CoreOS #26, perhaps they could be incorporated in subfolders? thank you!
AnneTheAgile

**Comment by aespinosa** [comment]
Re: Plugins - Internally Jenkins plugin data and other related configuration are found in JENKINS_HOME. You can persist them using a data container.

Re: Agents - If you expose the your isolated master's jnlp ports, any slave agent can connect to it. I've tried using my containers as masters for my windows slaves before.
